ibexa:
  repositories:
    default:
      checkout:
        workflow: product_availability_checkout

framework:
  workflows:
    product_availability_checkout:
      type: state_machine
      audit_trail:
        enabled: false
      marking_store:
        type: method
        property: status
      supports:
        - Ibexa\Contracts\Checkout\Value\CheckoutInterface
      initial_marking: initialized
      places:
        - initialized
        - product_availability
        - address_selected
        - shipping_selected
        - summarized
        - completed
      transitions:
        check_product_availability:
          from:
            - initialized
            - product_availability
            - address_selected
            - shipping_selected
            - summarized
          to:
            - product_availability
          metadata:
            next_step: select_address
            controller: App\Controller\Checkout\Step\ProductAvailabilityController
            label: 'Verify product availability'
        select_address:
          from:
            - initialized
            - product_availability
            - address_selected
            - shipping_selected
            - summarized
          to: address_selected
          metadata:
            next_step: select_shipping
            controller: Ibexa\Bundle\Checkout\Controller\CheckoutStep\AddressStepController::renderStepView
            label: 'Billing & shipping address'
            translation_domain: checkout
        select_shipping:
          from:
            - address_selected
            - shipping_selected
            - summarized
          to: shipping_selected
          metadata:
            next_step: summary
            controller: Ibexa\Bundle\Checkout\Controller\CheckoutStep\ShippingStepController::renderStepView
            label: 'Shipping & payment method'
            translation_domain: checkout
        summary:
          from:
            - shipping_selected
            - summarized
          to: summarized
          metadata:
            next_step: complete
            controller: Ibexa\Bundle\Checkout\Controller\CheckoutStep\SummaryStepController::renderStepView
            label: 'Payment & summary'
            translation_domain: checkout
        complete:
          from: summarized
          to: completed
          metadata:
            controller: Ibexa\Bundle\Checkout\Controller\CheckoutStep\CompleteStepController::renderCompleteView
            label: 'Order confirmation'
            translation_domain: checkout